### ISSUE TITLE
Demo is not working.

### ISSUE THREAD

**Issue by amritcoder** [tdausner/zipgallery#1]
I have downloaded your file and check but demo is not working.
An error alert i.e. Fehler beim Laden der Info aus Datei .
Please look into it. Thanks

**Comment by tdausner** [comment]
Can you please specify "demo is not working". Which URL?

**Comment by amritcoder** [comment]
This is an awesome script no doubt about this. I found nothing at no where for creating gallery for zip archive. I am very glad to see your fast response. First of all Thanks.
Now move on to the topic. I have downloaded this script and runs on wamp but I found 2 errors in both files i.e. fancybox.html & swiper.html both
1) at line no. 8 `<script type="text/javascript" src="../../concrete/js/jquery.js" ></script>` , this js file is not exist in downloaded file so I replace with it jquery-3.5.1.min.js 
2) after replacing js file script is little working to replace .zip url to without .zip url but when clicking on link an alert shows with an error i.e.
**Fehler beim Laden der Info aus Datei <http://tdsystem.eu/external/zipgallery/galleries/gallery-1.zip>
error**
If really @tdausner this script can create zip archive images into gallery than this script is more than awesome. Please look into it. Thanks

**Comment by tdausner** [comment]
Please pull and retry. Should work now.

**Comment by amritcoder** [comment]
Still It's not working , same error as above.
In galleries there is no zip file so I put there images.zip in which 4 photos and fetch through fancybox.html and swiper.html via this line 
**`<a class="gallery" href="/galleries/images.zip">Test gallery one</a>`**
But the error is same as previous we talk 
**Error loading info from file </galleries/images.zip>
error**
Please recheck the code and changes. I am very thankful for your effort and I hope it will sove very soon.
Thanks

**Comment by tdausner** [comment]
Ok please pull again. 
If you've downloaded my example ZIPs the anchor line now is
```
<a class="gallery" href="galleries/gallery-1.zip">Test gallery one</a>
```

**Comment by amritcoder** [comment]
Have you checked from your End ? Because it's still throws a same error with your new update . Let's do the things first put any demo zip folder inside gallery folder with 2 or 3 demo images and then test and update this script.  Thanks

**Comment by tdausner** [comment]
Yes, I've tested both:
* [https://tdsystem.eu/zipgallery/swiper.html](https://tdsystem.eu/zipgallery/swiper.html)
* [https://tdsystem.eu/zipgallery/swiper.html](https://tdsystem.eu/zipgallery/swiper.html)

How did I test?
* log into my web service at web site root (which is `~/www/tdsystem.eu`)
* clone from github: 
`git clone git@github.com:tdausner/zipgallery.git zipgallery`
* insert ZIP files: 
`cd zipgallery/galleries` 
`wget https://tdsystem.eu/external/zipgallery/galleries/gallery-1.zip`
`wget https://tdsystem.eu/external/zipgallery/galleries/gallery-2.zip`
`wget https://tdsystem.eu/external/zipgallery/galleries/fat-gallery.zip`

Here's the screenshot:

![image](https://user-images.githubusercontent.com/19776511/99294557-7d4cbb80-2844-11eb-946e-d6d83dfaade6.png)

**Comment by amritcoder** [comment]
Ok.
